version: "3"

services:
  nginx:
    container_name: nginx
    networks: inception_net
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      image: nginx
    env_file: .env
    restart: on-failure
    depends_on: wordpress
    ports: "443:443"
  mariadb:
    container_name: mariadb
    networks: inception_net
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      image: mariadb
    env_file: .env
    restart: on-failure
    expose: "3306"
  wordpress:
    container_name: wordpress
    networks: inception_net
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      image: wordpress
    env_file: .env
    restart: on-failure
    depends_on: mariadb
    expose: "9000"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/login/data/wordpress'

  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/login/data/mariadb'

networks:
	inception_net:
	driver: bridge
