version: "3"

services:
  nginx:
    container_name: nginx
    networks:
      - inception_net
    volumes:
      - wordpress:/var/www/wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - wordpress
    ports:
      - "443:443"
  mariadb:
    container_name: mariadb
    networks:
      - inception_net
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    restart: on-failure
    expose:
      - "3306"
  wordpress:
    container_name: wordpress
    networks:
      - inception_net
    volumes:
      - wordpress:/var/www/wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: on-failure
    depends_on: 
      - mariadb
    expose:
      - "9000"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/obednaou/data/wordpress'

  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/obednaou/data/mysql'

networks:
  inception_net:
    driver: bridge
